version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
  deploy-master:
    docker:
      - image: circleci/node:11.1.0

    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f2:60:78:96:3c:d5:74:7c:58:8a:86:1a:3b:e8:23:10"
      - run:
          name: Keyscan deploy server
          command: ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
      - run:
          name: Get the latest code
          command: ssh circleci@$DEPLOY_SERVER 'cd /opt/plun-backend && git pull'
      - run:
          name: Install dependencies
          command: ssh circleci@$DEPLOY_SERVER 'cd /opt/plun-backend && yarn install'
      - run:
          name: Build
          command: ssh circleci@$DEPLOY_SERVER 'cd /opt/plun-backend && yarn build'
      - run:
          name: Run
          command: ssh circleci@$DEPLOY_SERVER 'cd /opt/plun-backend && yarn start'

workflows:
  build-and-test:
    jobs:
      - build
      - deploy-master:
          filters:
            branches:
              only:
                - master
          requires:
            - build
